# Generated by Django 4.0.3 on 2022-03-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('DepartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentoNome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('FuncionarioId', models.AutoField(primary_key=True, serialize=False)),
                ('FuncionarioNome', models.CharField(max_length=500)),
                ('Departamento', models.CharField(max_length=500)),
                ('DataDeContratacao', models.DateField()),
                ('ArquivoFotoNome', models.CharField(max_length=500)),
            ],
        ),
    ]
